# Generated by Django 3.0.3 on 2020-02-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lombda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
